Feature/Update dashboard base components styling
hackmcgill/dashboard pull request #869
Opened 2020-10-10 20:33 UTC by Tony9984

### Tickets:

- HCK-#864

### List of changes:
Update styling of the following shared components:
 - [x] Buttons
 - [x] Checkboxes
 - [x] Text inputs
 - [x] Text area
 - [x] Select/multi-select

### Type of change:

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How did you do this?

### How to test:

### Questions:

### PR Checklist:

- [x] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [ ] Listed change(s) in the Changelog
- [x] Tested all links in project relevant browsers
- [x] Tested all links on different screen sizes
- [x] Referenced all useful info (issues, tasks, etc)

### Screenshots:

2020-10-10 20:44 UTC, logan-r requested changes
Looks great 🔥

Just the small changes listed and also fill out screenshots section

2020-10-10 20:44 UTC, logan-r commented on src/shared/Form/FormikElements/Checkbox.tsx
> +    box-shadow: 0px 0px 16px 0px rgba(16, 20, 55, 0.1);
nit: color should be from theme constant

2020-10-10 20:44 UTC, logan-r commented on src/shared/Styles/theme.ts
> +    purpleLight: 'rgba(92, 99, 171, 0.1)',
nit: change to #5C63AB19 for consistency

2020-10-10 21:48 UTC, logan-r requested changes
Good good

Could you also get rid of the border along the text inputs and increase border radius of buttons so they match the figma?

2020-10-10 21:51 UTC, logan-r commented
We're going to make the background an offwhite to increase the contrast and we'll probably end up making the box-shadow less pronounced then, but that can wait until after the backgrounds implemented so we can see how it looks

2020-10-10 21:55 UTC, Tony9984 commented
> Good good
> 
> 
> 
> Could you also get rid of the border along the text inputs and increase border radius of buttons so they match the figma?

Yeah sure!

2020-10-11 03:48 UTC, logan-r approved these changes
Good to merge!

2020-10-11 03:50 UTC, logan-r commented
Also when squashing and merging, have the message be something like "feat: update dashboard base components styling" as we use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

2020-10-11 05:42 UTC, merged